"use client";
import { useCallback, useEffect, useState } from "react";
import { FileCheck2, RefreshCw, ShieldAlert } from "lucide-react";
import { activateGstRules, approveGst, getGst, GstAdjustment, GstWorkpaper, packGst, prepareGst } from "./workpapers.api";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"});
export function GstWorkspace({clientId}:{clientId:string}){
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7));
 const [type,setType]=useState<"GSTR1"|"GSTR3B">("GSTR1"); const [paper,setPaper]=useState<GstWorkpaper|null>(null);
 const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const period=`${month.slice(5)}${month.slice(0,4)}`;
 const [adjustments,setAdjustments]=useState<GstAdjustment[]>([]);const [amount,setAmount]=useState("");const [reason,setReason]=useState("");
 const [component,setComponent]=useState("taxable_paise");const [table,setTable]=useState("GSTR-1 B2B");
 const load=useCallback(async()=>{try{setPaper((await getGst(clientId,period,type)).workpaper)}catch{setPaper(null)}},[clientId,period,type]);
 useEffect(()=>{void load()},[load]);
 const act=async(action:()=>Promise<GstWorkpaper>)=>{setBusy(true);setError("");try{setPaper(await action())}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}};
 const next=paper?.status==="NEEDS_REVIEW"?()=>act(()=>approveGst(paper.id)):paper?.status==="APPROVED"?()=>act(()=>packGst(paper.id)):()=>act(()=>prepareGst(clientId,period,type,adjustments));
 const label=paper?.status==="NEEDS_REVIEW"?"Approve snapshot":paper?.status==="APPROVED"?"Generate manual pack":"Prepare workpaper";
 return <div>
  <div className="flex flex-wrap items-end gap-3"><label className="text-xs font-medium text-[var(--muted)]">Return period<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="mt-1 block min-h-11 rounded-md border bg-white px-3 text-sm"/></label>
   <label className="text-xs font-medium text-[var(--muted)]">Return<select value={type} onChange={e=>{const next=e.target.value as typeof type;setType(next);setTable(next==="GSTR1"?"GSTR-1 B2B":"3.1(a) Outward taxable")}} className="mt-1 block min-h-11 rounded-md border bg-white px-3 text-sm"><option>GSTR1</option><option>GSTR3B</option></select></label>
   <button disabled={busy} onClick={()=>act(async()=>{await activateGstRules();return prepareGst(clientId,period,type,adjustments)})} className="min-h-11 rounded-md border bg-white px-4 text-sm font-medium disabled:opacity-50">Review official rules</button>
   <button disabled={busy||paper?.status==="READY_FOR_MANUAL_FILING"} onClick={next} className="btn-primary inline-flex min-h-11 items-center gap-2 rounded-md px-4 text-sm disabled:opacity-50">{busy?<RefreshCw className="h-4 w-4 animate-spin"/>:<FileCheck2 className="h-4 w-4"/>}{paper?.status==="READY_FOR_MANUAL_FILING"?"Pack ready":label}</button></div>
  {error&&<p role="alert" className="mt-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  <details className="mt-5 rounded-lg border bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Reviewer adjustments <span className="font-normal text-[var(--muted)]">({adjustments.length})</span></summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-[var(--muted)]">Table<input value={table} onChange={e=>setTable(e.target.value)} className="mt-1 h-11 w-full rounded-md border px-3 text-sm"/></label><label className="text-xs text-[var(--muted)]">Component<select value={component} onChange={e=>setComponent(e.target.value)} className="mt-1 h-11 w-full rounded-md border bg-white px-3 text-sm">{["taxable_paise","igst_paise","cgst_paise","sgst_paise","cess_paise"].map(item=><option key={item}>{item}</option>)}</select></label><label className="text-xs text-[var(--muted)]">Amount (₹)<input type="number" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 h-11 w-full rounded-md border px-3 text-sm"/></label><label className="text-xs text-[var(--muted)]">Reason<input value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 h-11 w-full rounded-md border px-3 text-sm"/></label></div><button disabled={!amount||reason.trim().length<3} onClick={()=>{setAdjustments(current=>[...current,{adjustment_id:crypto.randomUUID(),table_key:table,component,amount_paise:Math.round(Number(amount)*100),reason}]);setAmount("");setReason("")}} className="mt-3 min-h-11 rounded-md border px-4 text-sm font-medium disabled:opacity-50">Add adjustment</button></details>
  <div className="mt-6 rounded-xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.1em] text-[var(--muted)]">Review snapshot</p><h2 className="mt-2 text-xl font-semibold">{paper?paper.status.replaceAll("_"," "):"Not prepared"}</h2></div>{paper?.stale&&<span className="flex items-center gap-1 text-xs text-amber-800"><ShieldAlert className="h-4 w-4"/>Sources changed</span>}</div>
   {!paper?<p className="mt-8 text-sm text-[var(--muted)]">Prepare from verified registers. Source rows and versions will be bound to this workpaper.</p>:<><div className="mt-6 grid gap-3 sm:grid-cols-2">{Object.entries(paper.tables||{}).map(([key,value])=><div key={key} className="rounded-lg bg-[var(--panel)] p-4"><p className="text-xs font-medium text-[var(--muted)]">{key.replaceAll("_"," ")}</p><p className="mt-2 font-mono text-lg font-semibold">{money.format(value.total_paise/100)}</p><p className="mt-1 text-xs text-[var(--muted)]">Source {money.format(value.source_total_paise/100)} · Adjustments {money.format(value.adjustment_paise/100)}</p></div>)}</div>{!!paper.exceptions?.length&&<div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-semibold text-amber-900">Review required</p><ul className="mt-2 space-y-1 text-xs text-amber-800">{paper.exceptions.map((item,index)=><li key={`${item.code}-${index}`}>{item.message}</li>)}</ul></div>}</>}
  </div>
 </div>
}
