"""One connector contract for cloud and device-backed accounting systems."""
from abc import ABC, abstractmethod
from typing import Any
from connectors.platform.types import ApprovedAction, CanonicalObject, ConnectorResult, Cursor, ExecutionAttempt, Scope


class Connector(ABC):
    @abstractmethod
    async def probe(self) -> ConnectorResult[dict]: ...
    @abstractmethod
    async def get_capabilities(self) -> ConnectorResult[list[str]]: ...
    @abstractmethod
    async def list_masters(self, resource: str, cursor: Cursor) -> ConnectorResult[list[CanonicalObject]]: ...
    @abstractmethod
    async def list_transactions(self, resource: str, scope: Scope, cursor: Cursor) -> ConnectorResult[list[CanonicalObject]]: ...
    @abstractmethod
    async def get_object(self, object_type: str, provider_id: str) -> ConnectorResult[CanonicalObject]: ...
    @abstractmethod
    async def prepare_write(self, operation: str, canonical_payload: dict[str, Any]) -> ConnectorResult[dict]: ...
    @abstractmethod
    async def execute_write(self, approved_action: ApprovedAction, attempt: ExecutionAttempt) -> ConnectorResult[CanonicalObject]: ...
    @abstractmethod
    async def verify_write(self, provider_object: CanonicalObject, approved_payload: dict) -> ConnectorResult[dict]: ...
    @abstractmethod
    async def reconcile_changes(self, cursor: Cursor) -> ConnectorResult[list[CanonicalObject]]: ...
    @abstractmethod
    async def disconnect(self) -> ConnectorResult[None]: ...
